import type { NextPage } from "next";
import Head from "next/head";
import { useEffect } from "react";
import { client } from "../config/client";

const Home: NextPage = (props) => {
  useEffect(() => {
    console.log(props);
  }, []);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-xl font-bold text-red-400 ">Hello World</h1>
      </main>
    </div>
  );
};

export const getStaticProps = async () => {
  const data = await client.get({
    endpoint: "blogs",
  });

  return {
    props: {
      data,
    },
  };
};

export default Home;
